//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cart
{
    public int CartId { get; set; }
    public int Id { get; set; }
    public int Waterid { get; set; }
    public int Count { get; set; }
}

public partial class Employee
{
    public int ID { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Password2 { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public System.DateTime Birthday { get; set; }
    public string Address { get; set; }
    public string CellPhone { get; set; }
    public string HomePhone { get; set; }
    public string Department { get; set; }
    public string Position { get; set; }
    public System.DateTime HireDay { get; set; }
    public Nullable<System.DateTime> Resignday { get; set; }
    public int Salary { get; set; }
    public int Extension { get; set; }
    public string ImageName { get; set; }
}

public partial class MeetingRoom
{
    public string UserName { get; set; }
    public string Room { get; set; }
    public string Date { get; set; }
    public string Time { get; set; }
    public string Reason { get; set; }
    public string Approval { get; set; }
}

public partial class mySchedule
{
    public int Id { get; set; }
    public string UserName { get; set; }
    public string EventName { get; set; }
    public string StartDate { get; set; }
    public string StartTime { get; set; }
    public string EndDate { get; set; }
    public string EndTime { get; set; }
    public string IsAllDay { get; set; }
    public string Loginer { get; set; }
}

public partial class Sponsor
{
    public int Waterid { get; set; }
    public int Id { get; set; }
    public string ProductName { get; set; }
    public int Price { get; set; }
    public Nullable<int> LimitCount { get; set; }
    public string ProductInFo { get; set; }
    public string SayST { get; set; }
    public string ImgFileName1 { get; set; }
    public string ImgFileName2 { get; set; }
    public string ImgFileName3 { get; set; }
    public string Check { get; set; }
    public bool PDStatus { get; set; }
    public Nullable<int> PDCountNow { get; set; }
    public string RJresult { get; set; }
}

public partial class ToDoList
{
    public int Id { get; set; }
    public string UserName { get; set; }
    public string myEvent { get; set; }
}
